### ISSUE TITLE
TypeError: Cannot call method 'map' of undefined

### ISSUE THREAD

**Issue by 1jerry** [carrot/ship#54]
-to gh-pages prompts me.  -to s3 prompts me.  -to heroku spits at me in 0.1.1 AND 0.1.2:
$ /b/VCS/ship/bin/ship -v
0.1.2

Jerry@HEART /b/node/roots-demo (master)
$ /b/VCS/ship/bin/ship -to heroku
Please enter the following config details for heroku
Need help? see http://carrot.github.io/ship/heroku

b:\VCS\ship\lib\prompt.coffee:28
    questions = required.map(function(v) {
                         ^
TypeError: Cannot call method 'map' of undefined
  at module.exports (b:\VCS\ship\lib\prompt.coffee:23:24)
  at Ship.config_prompt (b:\VCS\ship\lib\index.coffee:66:5)
  at CLI.run (b:\VCS\ship\lib\cli.coffee:59:12)
  at Object.<anonymous> (b:\VCS\ship\bin\ship:19:5)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
- node 0.10.2
- Windows 8
- GNU bash, version 3.1.0(1)-release (i686-pc-msys)
- git version 1.9.4.msysgit.0

**Comment by declandewet** [comment]
I'm getting this same error for Netlify on Yosemite - but the deployer *does* have it's required array, so I'm not sure what the fix is

**Comment by jenius** [comment]
Make sure you are on the latest version of ship, and if this is through roots that you have run `roots tpl reset`

**Comment by declandewet** [comment]
this is through roots, ran `roots tpl reset` but still getting the error

**Comment by jenius** [comment]
What version of roots are you on?

**Comment by declandewet** [comment]
V3 stable

**Comment by jenius** [comment]
Something must be very wrong then. We have been using the netlify deployer with roots v3 stable for quite a while and it works fine. Is there any way you could dig in a little further? This issue is almost certainly specific to your machine since it works for everyone else and is tested, but I still want to make sure we can resolve it...

**Comment by jenius** [comment]
I'm sorry @declandewet and @hhsnopek I am a huge idiot, I patched this but didn't ship the patch. This now works. Run `npm i roots -g` to update roots and you will be all set.
