### ISSUE TITLE
deploy triggered abuse warning from github

### ISSUE THREAD

**Issue by newswim** [carrot/ship#79]
I'm using Roots, whose `deploy` command is a wrapper for Ship, but i'll post this over there as well (I assume the same fellas are checking this).

I have not updated to Roots v4 yet.

```

{ [Error: {
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
}
]
  message: '{\n  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",\n  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."\n}\n',
  code: 403 }
Potentially unhandled rejection [4] {
  "documentation_url": 
  "message": 
}
```

This occurred for the first time today.

**Comment by newswim** [comment]
Looks like my assets folder was getting too big. Deleted some extra things and deploy works now. I definitely think this is a github thing and not to do with Ship.

**Comment by samccone** [comment]
:+1:
